version: "3.7"

services:
  backend:
    build:
      context: backend
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - db

  frontend:
    build:
      context: frontend
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - backend

  db:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
